name: Deploy React App to Pages

on:
  push:
    branches: ["releases"] # Csak akkor fut le, ha a "releases" ágra pusholsz. Biztos ez a fő branched? Ha nem, írd át main-re!
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: 'npm'

      - name: Install dependencies
        run: cd konyvkocka && npm install

      - name: Build project
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Ez a legfontosabb: a 'dist' mappát töltjük fel, nem a gyökeret!
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
